apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdevkit-service
  namespace: webdevkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdevkit-service
  template:
    metadata:
      labels:
        app: webdevkit-service
    spec:
      containers:
        - name: service
          image: webdevkit-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: WEBDEVKIT_SERVICE_PORT
              value: "3001"
