apiVersion: v1
kind: Service
metadata:
  name: webdevkit-service
  namespace: webdevkit
spec:
  type: ClusterIP
  selector:
    app: webdevkit-service
  ports:
    - name: http
      port: 3001
      targetPort: 3001
