apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdevkit-web
  namespace: webdevkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdevkit-web
  template:
    metadata:
      labels:
        app: webdevkit-web
    spec:
      containers:
        - name: web
          image: webdevkit-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: VITE_WEBDEVKIT_SERVICE_URL
              value: "http://webdevkit-service:3001"
